FROM debian:13
USER root

# Add DS/DN repo
RUN apt-get update && apt-get -y install curl gpg \
    && curl -sS http://packages.demarches-simplifiees.fr/KEY.gpg | gpg --dearmor -o /usr/share/keyrings/demarches-simplifiees.gpg \
    && echo "deb [signed-by=/usr/share/keyrings/demarches-simplifiees.gpg] http://packages.demarches-simplifiees.fr/jammy /" > /etc/apt/sources.list.d/packages_demarches_simplifiees_fr_jammy.list \
    && apt-get update && apt-get -y install ds-proxy \
    && adduser --disabled-password --gecos "" ds_proxy \
    && apt-get remove --purge -y curl gpg \
    && apt-get clean

USER ds_proxy

EXPOSE 4444

ENTRYPOINT ["/usr/bin/ds_proxy"]
